In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
cd /raid/home/myang349/recsys-filterbubbles/

/raid/home/myang349/recsys-filterbubbles


In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import torch.optim as optim
from os import listdir
from os.path import isfile, join
from tracin.tracin import (
    save_tracin_checkpoint,
    load_tracin_checkpoint,
    calculate_tracin_influence,
)
import pandas as pd
from LSTM_clean.utils import train_test_split, sequence_generator, printl
from LSTM_clean.model import LSTM 
from collections import Counter
import numpy as np
import pickle

In [5]:
os.getcwd()

'/raid/home/myang349/recsys-filterbubbles'

In [6]:
DATA_FOLDER = "/raid/home/myang349/recsys-filterbubbles/data/"
DATA_NAME = "twitch100k.csv"
USER_KEY = 'user_id'
ITEM_KEY = 'streamer_name'
TIME_KEY = 'stop_time'
LOOK_BACK = 50

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device is ", device)


Device is  cuda


# Loading Data

In [8]:
print(f"Starting data retrieval for: {DATA_NAME}")
df = pd.read_csv(os.path.join(DATA_FOLDER, DATA_NAME))

Starting data retrieval for: twitch100k.csv


In [14]:
# Not needed because it is already done by the sequence generator function
# if 0 in df['streamer_name'].values:
#     df['streamer_name'] = df['streamer_name'].apply(lambda x: x + 1)

In [21]:
data = df[[USER_KEY, ITEM_KEY, TIME_KEY]]
data = data.values

In [22]:
unique_users = sorted(list(set(data[:, 0])))
unique_items = sorted(list(set(data[:, 1])))

In [23]:

user_dic = {user:idx for (idx,user) in enumerate(unique_users)}
item_dic = {item:idx for (idx,item) in enumerate(unique_items)}

# for (idx, row) in enumerate(data):
#     user,item,time = user_dic[row[0]],item_dic[row[1]],row[2]
#     data[idx,0],data[idx,1] = int(user),int(item)

In [40]:
train[0][0].shape

torch.Size([49, 128])

In [42]:
train[1][0].shape

torch.Size([49, 128])

In [44]:
items_per_user = {int(user) : [0 for i in range(LOOK_BACK)] for user in unique_users}

In [46]:
# In[5] Data preprocessing
print("Preprocessing Data")
original_data = train_test_split(data=data)
(train,valid, test) = sequence_generator(original_data,LOOK_BACK)
test_ground_truth = {i:test[i][1] for i in range(len(test))}

print("Train: {}, Test: {}".format(len(train),len(test)))



# # %%
# # In[6] Run LSTM
# model = LSTM(input_size=128, output_size=len(unique_items)+1, hidden_dim=64, n_layers=1, device=device).to(device)
# model.LSTM.flatten_parameters()
# print("Model is ", model)
# print("Training and testing")
# original_prediction = model.traintest(train=train,test=test,epochs = 500)
# print("Finished")

Preprocessing Data


In [65]:
with open(f"{DATA_FOLDER}sequence/temp.data", 'wb') as f:
    pickle.dump(train, f)

In [67]:
with open(f"{DATA_FOLDER}sequence/temp.data", "rb") as f:
    data = pickle.load(f)

In [70]:
os.path.getsize(f"{DATA_FOLDER}sequence/temp.data")

11056373

# junk below

In [ ]:
assert torch.cuda.is_available()
device = torch.device("cuda")
print(f"Device is: {device}")

In [28]:
df = pd.read_csv(os.path.join(DATA_FOLDER, DATA))

In [29]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device is ", device)


# In[4] Load data (ex: wikipedia [user, item, timestamp])
print("Loading data")
path = os.getcwd()
raw_data = pd.read_csv(path + "/data/twitch100k.csv", sep=',', header=0)
print(raw_data.head())
# streamer_community_dict = pd.Series(raw_data['community'].values, index=raw_data['streamer_name']).to_dict()
data = raw_data[['user_id', 'streamer_name', 'stop_time']]
print(data.head())
data = data.values
look_back = 50
print(data)

Device is  cuda
Loading data
   user_id    stream_id  streamer_name  start_time  stop_time  community
0        1  33842865744              0         154        156          5
1        1  33846768288              1         166        169          5
2        1  33886469056              0         587        588          5
3        1  33887624992              2         589        591          5
4        1  33890145056              3         591        594          5
   user_id  streamer_name  stop_time
0        1              0        156
1        1              1        169
2        1              0        588
3        1              2        591
4        1              3        594
[[   1    0  156]
 [   1    1  169]
 [   1    0  588]
 ...
 [4416 1515 4015]
 [4416 1984 4008]
 [4416 2375 4022]]


In [73]:
len(set(df['streamer_name']))

5672

In [72]:
max(df['streamer_name'])

5671

In [9]:
nums = [1,2,3]

In [10]:
x, y, z = nums

In [11]:
x

1